# Base configs
baseurl: "http://zerunphotography.top"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "Photography by Wang Zerun"
subtitle: "Shoot my world"
author: "Wang Zerun"
header:
 title: "Photography"
 subtitle: "by Wang Zerun"
footer:
 name: "Hey there, my name is Zerun"
 bio: "I am a high school student. I loves photography and using computer to improve myself."
 github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork Ram on github</a> ;)"
web_design: "AJ"
social_urls:
#  facebook: "https://www.facebook.com/ramswaroop"
#  twitter: "https://www.twitter.com/ramswarooppatra"
#  instagram: "https://www.instagram.com/ramswarooppatra"
#  dribbble: "https://dribbble.com/ramswaroop"
#  linkedin: "https://in.linkedin.com/in/ramswarooppatra"
  github: "https://www.github.com/tanzantite999"
